doctrine_migrations:
    migrations_paths: 
        'App\Migrations': '%kernel.project_dir%/migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    # old: namespace: DoctrineMigrations
