services:
  app:
    build:
      dockerfile: Dockerfile.dev
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
      - var_data:/var/www/var

  web:
    build:
      dockerfile: Dockerfile.web.dev
    volumes:
      - ./:/var/www

volumes:
  vendor_data:
  var_data:
