services:
  app:
    build:
      dockerfile: Dockerfile.dev
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
      - var_data:/var/www/var

  web:
    image: nginx:1.29-alpine
    volumes:
      - ./resources/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www

volumes:
  vendor_data:
  var_data:
