FROM composer:latest as composer
WORKDIR "/app"
COPY composer.json composer.lock symfony.lock ./

# composer install ausführen jedcoh ohne scripts und autloader
# da noch nicht die ganze soure reinkopiert wurde. Grund: Caching
# Wenn die Source bereits am Anfang reinkopiert würde, würde bei jeder Codeänderung 
# bei Rebuild composer install erneute ausgeführt werden und könnte nicht vom Cache geladen werden.

RUN composer install --no-scripts --ignore-platform-req=ext-gd

FROM alpine:3.22
WORKDIR /var/www

RUN apk --update add --no-cache \
	php84  \
	php84-fpm  \
	php84-dom  \
	php84-tokenizer  \
	php84-pdo  \
	php84-pdo_pgsql  \
	php84-mbstring  \
	php84-openssl  \
	php84-xml  \
	php84-xmlwriter \
	php84-xmlreader \
	php84-fileinfo \
	php84-simplexml  \
	php84-session  \
	php84-zip  \
	php84-gd \
	php84-phar
RUN ln -sf /usr/bin/php84 /usr/bin/php

RUN apk add curl
RUN apk add git
COPY --from=composer /usr/bin/composer /usr/local/bin/composer

COPY ./resources/php/php.ini /etc/php84/php.ini
COPY ./resources/php/zz-docker-env.conf /etc/php84/php-fpm.d/zz-docker-env.conf
COPY --from=composer /app /var/www
COPY . .

RUN ./bin/console cache:warmup --env=prod
RUN ./bin/console assets:install --env=prod

RUN mkdir -p /var/www/var/cache/dev/doctrine/orm/Proxies /var/www/var/log
RUN chmod -R a+rwX /var/www/var

EXPOSE 9000

CMD ["php-fpm84", "-F"]
