FROM composer:latest as composer
WORKDIR "/app"
COPY composer.json composer.lock symfony.lock ./

# composer install ausführen jedcoh ohne scripts und autloader
# da noch nicht die ganze soure reinkopiert wurde. Grund: Caching
# Wenn die Source bereits am Anfang reinkopiert würde, würde bei jeder Codeänderung 
# bei Rebuild composer install erneute ausgeführt werden und könnte nicht vom Cache geladen werden.

RUN composer install --no-scripts

FROM nginx:1.15.8-alpine
EXPOSE 80
WORKDIR "/var/www"
# alpine removes packages!: https://medium.com/@stschindler/the-problem-with-docker-and-alpines-package-pinning-18346593e891
ENV php7version 7.2.17-r0

RUN apk --update add --no-cache \
	php7=$php7version \
	php7-dom=$php7version \
	php7-fpm=$php7version \
	php7-ctype=$php7version \
	php7-json=$php7version \
	php7-pdo=$php7version \
	php7-tokenizer=$php7version \
	php7-session=$php7version \
	php7-mbstring=$php7version \
	php7-iconv=$php7version \
	php7-xml=$php7version \
	php7-simplexml=$php7version \
	php7-pgsql=$php7version \
	php7-openssl=$php7version \
	php7-pdo_pgsql=$php7version

COPY ./resources/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./resources/php/php.ini /etc/php7/php.ini
COPY --from=composer /app /var/www
COPY . .
RUN ./bin/console cache:clear
RUN chmod a+x ./docker/run_nginx_php.sh
#CMD ./var/www/docker/run_nginx_php.sh
CMD ["./docker/run_nginx_php.sh"]